#include "StdAfx.h"
#include "toString.h"
#include "config.h"

//-----------------------------------------------------------------------------

const char*	toString( HRESULT hr )
{
	switch ( hr )
	{
	case DS_OK: return "DS_OK"; 
	case DSERR_ALLOCATED: return "DSERR_ALLOCATED";
	case DSERR_CONTROLUNAVAIL: return "DSERR_CONTROLUNAVAIL";
	case DSERR_INVALIDPARAM: return "DSERR_INVALIDPARAM";
	case DSERR_INVALIDCALL: return "DSERR_INVALIDCALL";
	case DSERR_GENERIC: return "DSERR_GENERIC";
	case DSERR_PRIOLEVELNEEDED: return "DSERR_PRIOLEVELNEEDED";
	case DSERR_OUTOFMEMORY: return "DSERR_OUTOFMEMORY";
	case DSERR_BADFORMAT: return "DSERR_BADFORMAT";
	case DSERR_UNSUPPORTED: return "DSERR_UNSUPPORTED";
	case DSERR_NODRIVER: return "DSERR_NODRIVER";
	case DSERR_ALREADYINITIALIZED: return "DSERR_ALREADYINITIALIZED";
	case DSERR_NOAGGREGATION: return "DSERR_NOAGGREGATION";
	case DSERR_BUFFERLOST: return "DSERR_BUFFERLOST";
	case DSERR_OTHERAPPHASPRIO: return "DSERR_OTHERAPPHASPRIO";
	case DSERR_UNINITIALIZED: return "DSERR_UNINITIALIZED";
	case DSERR_NOINTERFACE: return "DSERR_NOINTERFACE";
	case DSERR_ACCESSDENIED: return "DSERR_ACCESSDENIED";
	case DSERR_BUFFERTOOSMALL: return "DSERR_BUFFERTOOSMALL";
	case DSERR_DS8_REQUIRED: return "DSERR_DS8_REQUIRED";
	case DSERR_SENDLOOP: return "DSERR_SENDLOOP";
	case DSERR_BADSENDBUFFERGUID: return "DSERR_BADSENDBUFFERGUID";
	case DSERR_OBJECTNOTFOUND: return "DSERR_OBJECTNOTFOUND";
	case DSERR_FXUNAVAILABLE: return "DSERR_FXUNAVAILABLE";
	default: return "DSERR_UNKNOWN";
	}
}
